### ISSUE TITLE
New version support calendar?

### ISSUE THREAD

**Issue by omnibs** [arianvp/dhall-kubernetes#146]
There's a growing set of problems I've been facing managing Helm charts which `dhall-kubernetes` can solve, I want to adopt, but I don't want it to hold me back from upgrading to a new Kubernetes version. K8S 1.19 has been out for a month and I'm not sure from looking at the repo when I can expect `dhall-kubernetes` to add support.

Is it possible to document a release calendar / support calendar in the readme or somewhere? I'm thinking "`dhall-kubernetes` adds support to new Kubernetes versions within X months. Versions are supported for up to X years".

I realize this means the project would commit to a release calendar, and it might not have the bandwidth to commit, but making that explicit would be helpful too.

**Comment by Gabriella439** [comment]
@omnibs: Oh, it's actually very easy for us to support new Kubernetes versions because the process is almost entirely automated via our `./scripts/add-kubernetes-release.sh` script (especially after https://github.com/dhall-lang/dhall-kubernetes/pull/148 is merged).

The only reason we haven't added support for 1.19 yet is because I don't closely follow Kubernetes releases, but if somebody requests me to add support for a new Kubernetes version, it's easy for me (or any other person) to do.  Also, if there is a low-volume way I can get notified of new Kubernetes releases I can take care of releasing them when they come out.

Basically, this is a long-winded way of saying that we can easily support a new Kubernetes release within a day of the release (modulo weekends/holidays/vacation/etc.).

As far as a support calendar goes, we currently have no issues supporting releases indefinitely (since we haven't yet run into any technical issues with supporting older releases).  The only soft limitation we will eventually hit is the size of the repository (due to the large number of generated files), but we still haven't gotten to the point where it's a problem, yet.

I also went ahead and created a pull request to add support for API version 1.19: https://github.com/dhall-lang/dhall-kubernetes/pull/147

**Comment by omnibs** [comment]
Oh wow, that's awesome :D I assumed there was some manual labor involved in keeping things working / making new things work.

We can assume then if anyone is missing a new version, anyone can add it using the release script, plus if folks struggle, it wouldn't be unpolite to ask =]

Going to go ahead and close this

**Comment by Gabriella439** [comment]
@omnibs: Yeah, that's correct!  Anybody can feel free to ask me to do it or open a pull request themselves
