### ISSUE TITLE
Production usage

### ISSUE THREAD

**Issue by shinzui** [arianvp/dhall-kubernetes#157]
Is anyone using `dhall-kubernetes` in production for a relatively complex project? We're currently not happy with Helm and evaluating moving 100s of helm chart to something that allows more reuse. I've been aware of `dhall-kubernetes` for some time, but I just started doing research on the helm alternatives.

**Comment by TristanCacqueray** [comment]
Here is an operator I wrote to deploy a CI system named Zuul: https://opendev.org/zuul/zuul-operator/src/branch/master/CONTRIBUTE.md . This is mostly a dhall function that takes the CRD as an input and produce the list of kubernetes resources.

**Comment by Gabriella439** [comment]
@shinzui: The biggest issue you'll run into when building a "Helm for Dhall" is that performance will start to slow down (mainly due to being bottlenecked on the cache), for reasons described in this issue:

https://github.com/dhall-lang/dhall-haskell/issues/1890

The second issue you'll run into is the ergonomics of customizing resources, and this Discourse thread discusses the roadmap for improving that:

https://discourse.dhall-lang.org/t/roadmap-for-improved-kubernetes-support/313

**Comment by shinzui** [comment]
@TristanCacqueray Did you encounter any performance problems or incomplete types for Kubernetes resources? 

@Gabriel439 Thank you for the links. That's exactly what I was looking for. My use case is similar to the one outlined in dhall-lang/dhall-haskell#1890. It sounds like my best bet is to wait for the performance to improve. I'm still going to try `dhall-Kubernetes` on one of our complex helm charts to evaluate it.

**Comment by TristanCacqueray** [comment]
It does takes time to evaluate the configuration (about 10sec), but that's not a blocker. The dhall-kubernetes types work fine for this use-case, they are only missing the Cert-Manager, and here is how they are added locally: https://opendev.org/zuul/zuul-operator/src/branch/master/conf/CertManager.dhall#L53-L57

**Comment by TristanCacqueray** [comment]
To improve the performance today, you can reduce the size of dhall-kubernetes to what you need by creating a custom package and union, here is a small script I wrote to do that: https://github.com/TristanCacqueray/dhall-openshift/blob/mini-package/mini-generate.py

**Comment by shinzui** [comment]
Thank you, @TristanCacqueray.
