### ISSUE TITLE
Newer Kubernetes releases

### ISSUE THREAD

**Issue by fabfianda** [arianvp/dhall-kubernetes#169]
Hi guys, amazing project!
I'd like to know if K8s releases from v1.20 and on will be supported as well.

Thanks!

**Comment by Gabriella439** [comment]
Yep!  It's easy for us to add new releases and I created a PR for adding 1.20 and 1.21: https://github.com/dhall-lang/dhall-kubernetes/pull/170

Just ping us to add a new release any time.  I don't track Kubernetes releases closely myself, so I usually won't know to add one unless somebody asks.

Also, anybody who has Nix installed can do the process themselves instead of waiting on me.  All I do is run:

```bash
$ ./scripts/add-kubernetes-release X.Y
$ ./scripts/generate
```

**Comment by fabfianda** [comment]
thanks Gabriel, you're a rockstar!

**Comment by Gabriella439** [comment]
You're welcome! 🙂
