### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by f-f** [arianvp/dhall-kubernetes#17]
From #16 we'll have a script to typecheck all the generated files, and as mentioned in https://github.com/dhall-lang/dhall-kubernetes/pull/14#pullrequestreview-135229951 it would be nice to have CI check a set of end-to-end examples so that we don't inadvertently break users.

/cc @Gabriel439 should we use the Hydra instance as all the other repos, and if yes what's missing to make it work?

**Comment by Gabriella439** [comment]
I can set up the Hydra instance to build `dhall-kubernetes`.  The steps that are involved are making a change to the nixops specification here:

https://github.com/dhall-lang/dhall-lang/blob/master/nixops/logical.nix

... and then redeploying it.  Anybody can in theory make the change, but only I can redeploy it because `nixops` doesn't have a good story for secure shared deployment, so usually I just do this part.

For more details, see:

https://github.com/dhall-lang/dhall-lang/blob/master/nixops/README.md

The changes you need to make on your end are adding a `release.nix` file to the repository that can be built using the following command:

```bash
$ nix-build release.nix
```

That needs to have a record where one field is a build named `dhall-*` (i.e. `dhall-kubernetes`) and then Hydra will use that success of that build to mark your pull request revisions

**Comment by Gabriella439** [comment]
Alright, it's up now and you can view the Hydra page for this project's pull requests here:

http://hydra.dhall-lang.org/project/dhall-kubernetes

Once you add a `release.nix` file those builds will begin to succeed

The matching pull request to update the `nixops` configuration is here:

https://github.com/dhall-lang/dhall-lang/pull/185
