### ISSUE TITLE
The deployment.dhall example is broken

### ISSUE THREAD

**Issue by neongreen** [arianvp/dhall-kubernetes#44]
I'm using dhall-to-json-1.2.6 (corresponding to dhall-1.20).

```
$ (cd examples; dhall-to-yaml < deployment.dhall)


↳ ./../api/Deployment/mkDeployment
  ↳ ./../api/Deployment/RawDefaults

Error: Field mismatch

{ deployment    = ../../default/io.k8s.api.apps.v1.Deployment.dhall
, container     = ../../default/io.k8s.api.core.v1.Container.dhall
, containerPort = ../../default/io.k8s.api.core.v1.ContainerPort.dhall
======================================================================
, Int           = intOrString.Int
, String        = intOrString.String
}
/Users/yom/code/dhall-kubernetes/examples/../api/Deployment/RawDefaults:4:1
```

**Comment by f-f** [comment]
@neongreen yes, this is due to the fact that dhall-haskell 1.20 broke compatibility wrt to the `constructors` keyword (that is used in `IntOrString` you see in the error), and we haven't upgraded yet (I have the fix locally already, I'll push it later today)

Dhall 1.19 and dhall-json 1.2.5 should work (IIRC this is the version we run at work)

**Comment by f-f** [comment]
@neongreen fix up in #45, could you try it and see if it works for you?

**Comment by neongreen** [comment]
Yep, it does.

**Comment by f-f** [comment]
Great. Thanks for reporting!
