### ISSUE TITLE
[RFC]: Resolve defaults recursively

### ISSUE THREAD

**Issue by arianvp** [arianvp/dhall-kubernetes#46]
For example, for a deployment:

instead of filling each default with the obvious "empty type" of a field, recursively resolve the default values.

so instead of this:
```dhall
\(_params : {metadata : (../types/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.dhall)}) ->
{ apiVersion = ("apps/v1" : Text)
, kind = ("Deployment" : Text)
, metadata = _params.metadata
, spec = ([] : Optional (../types/io.k8s.api.apps.v1.DeploymentSpec.dhall))
, status = ([] : Optional (../types/io.k8s.api.apps.v1.DeploymentStatus.dhall))
} : ../types/io.k8s.api.apps.v1.Deployment.dhall
```

this:
```
{ apiVersion = ("apps/v1" : Text)
, kind = ("Deployment" : Text)
, metadata =  ../default/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.dhall
, spec =  ../default/io.k8s.api.apps.v1.DeploymentSpec.dhall
, status = ../default/io.k8s.api.apps.v1.DeploymentStatus.dhall
} : ../types/io.k8s.api.apps.v1.Deployment.dhall
```

This makes a "merge" based API where we compose layers of configurations with `//` way more natural. Similar to https://kustomize.io

**Comment by arianvp** [comment]
I'm not sure how well this approach pans out in the presence of required arguments, which we currently handle as a lambda...

Perhaps we can have a type for defaults, and a type for full specs,   such that   

`Deployment =   DeploymentDefault // {  metadata  : ObjectMeta.dhall }`

one can then write:

```
mydeployment  = ({ metadata = blah } //  (defaultDeployment : DefaultDeployment)) : Deployment
```

**Comment by arianvp** [comment]
Oh :(   You can only combine records,  not types at the moment: https://github.com/dhall-lang/dhall-lang/issues/175#issuecomment-397663153

**Comment by arianvp** [comment]
Also, this seems related : https://github.com/dhall-lang/dhall-lang/issues/340  and seems to describe the behaviour I want.   so doesn't seem possible with dhall currently :(

**Comment by arianvp** [comment]
More complicated example of how this would look, taking into account https://github.com/dhall-lang/dhall-lang/issues/340

It's not great, but it's better than the current raw API in my opinion

```
let 
  default = ./default/Deployment.dhall 
  mydeployment = default // { 
    metadata =  { name = "hello" },
    spec = let default = default.spec in (default.spec // {
      replicas = Some 3, 
      template = default.template // {
        spec = let default = default.spec in (default.spec // {
          containers = let default = ./default/Container.dhall in [
            default // {
              image = "nginx",
              ports = default.ports // {
                containerPort = 80
              }
            },
          ]
        })
      }
    })
  }


```

**Comment by Gabriella439** [comment]
@arianvp: You can merge record types, using `⩓`.  You just can't override the type of a record type's field.

**Comment by f-f** [comment]
@arianvp I very much like the idea, but after thinking a bit about this I have some implementation questions:
1. if we recursively resolve the default value instead of having `None` for optional values, is there is a semantic difference for Kubernetes between "the field is not there" and "the field is there but the object is empty"?
2. related to above: the yaml files in output would get HUGE. Currently they are tiny because we have mostly `None`s, and we run `dhall-to-yaml --omitNull`. I think this would get pretty unappealing, since readability of the results would likely be lower
3. where should we draw the line? Should we stop the recursion at the first record that contains a required field?

**Comment by Gabriella439** [comment]
@f-f: Note that I can extend `dhall-to-yaml` so that `--omitNull` also omits records whose transitive fields are all `None`

This is something that `dhall-nethack` does, where if a field is a record then it's not wrapped in `Optional` and it is always present.  Then the default outer record initializes the inner record to all default values

**Comment by f-f** [comment]
@Gabriel439 I didn't consider that we could handle this in `dhall-to-yaml` :)

Cool, then let's go for this 👍

**Comment by arianvp** [comment]
> @f-f: Note that I can extend dhall-to-yaml so that --omitNull also omits records whose transitive fields are all None

I would put this behind a flag, just to be sure.  I'm pretty sure there's software in the wild that depends on just "existence" of keys for example

**Comment by Gabriella439** [comment]
@arianvp: Wouldn't that imply that the software wouldn't be using `--omitNull` anyway?

Or in other words, is there software in the wild that works correctly when you omit null fields, but misbehaves when you omit empty records?

**Comment by Gabriella439** [comment]
@arianvp @f-f: Here is the pull request to add a new `--omitEmpty` flag for this purpose: https://github.com/dhall-lang/dhall-haskell/pull/842
