### ISSUE TITLE
JSONSchemaProps.dhall references itself (Cyclic import)

### ISSUE THREAD

**Issue by jvanbruegge** [arianvp/dhall-kubernetes#47]
When trying to create a custom resource definition, dhall errors with

```
↳ ./../dhall-kubernetes/default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition.dhall
  ↳ ./../dhall-kubernetes/types/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec.dhall
    ↳ ./../dhall-kubernetes/types/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceValidation.dhall
      ↳ ./../dhall-kubernetes/types/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps.dhall

Cyclic import: ./io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps.dhall
```

The reason is that `JSONSchemaProps` [references itself](https://github.com/dhall-lang/dhall-kubernetes/blob/bc09fbe1b48d2ec902e0fd7a3883ae51a59e6222/types/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps.dhall#L5) (at least I think that's the issue)

**Comment by jvanbruegge** [comment]
Could possibly be fixed by copying the file, remove all fields that reference itself and use the copy in the place of the self-reference in the original file. So you would have 1 layer of recursion and not infinite

**Comment by jvanbruegge** [comment]
For reference, my quick&dirty fix: https://github.com/jvanbruegge/dhall-kubernetes/commit/110e5e4f7abf5da875df922ee4775668145c776c works as intented

**Comment by f-f** [comment]
@jvanbruegge yes, this is a known bug and the reason is indeed the cyclic imports. In fact we do run tests on all the generated Dhall definitions, and the ones you stumbled on are [the only ones that don't compile](https://github.com/dhall-lang/dhall-kubernetes/blob/master/scripts/check-source.py#L15)

Now, I don't have a "good" fix for this, so any of your fixes (0 or 1 levels of recursion) would be good 👍 (an imperfect definition that compiles is better than a perfect one that doesn't)
