### ISSUE TITLE
Generate top-level union type for all apis

### ISSUE THREAD

**Issue by arianvp** [arianvp/dhall-kubernetes#54]
Basically, make this auto-generated instead of written by hand: https://github.com/dhall-lang/dhall-kubernetes/issues/48#issuecomment-473676761

**Comment by f-f** [comment]
@arianvp I just started rewriting this in Haskell as the current python script is getting out of hand, I'll add this too.

**Comment by ari-becker** [comment]
A word of caution - we have some deeply nested union types over at [dhall-concourse](https://github.com/coralogix/dhall-concourse) and it drastically increases the compute and time resources needed by `dhall-to-yaml` as the normal forms start to explode in size. They're not nearly as big as a giant union of all the Kubernetes types would be, so while I'm sympathetic to the desire for a union of all the Kubernetes API objects, I shudder to think at the performance.

**Comment by arianvp** [comment]
Thanks for the warning. I don't think this should stop us from implementing this though. People can always opt for generating multiple YAML files instead of returning one large YAML file.  Instead it should serve as a benchmark to make the Dhall implemention more performant :)

**Comment by ari-becker** [comment]
I thought of something else - since I maintain [dhall-prometheus-operator](https://github.com/coralogix/dhall-prometheus-operator) as well. Currently Dhall doesn't support merging union types, which is to say, there's currently no way to do something like `<A : a | B : b> ⩓ <C : c | D : d >` to get `<A : a | B : b | C : c | D : d >`. This is relevant because any auto-generated union of all the Kubernetes API objects necessarily wouldn't include any CRDs defined by the user, and the user has no way of getting a union that includes the user's CRDs.

Perhaps that's not a reason to oppose implementation (surely there's benefit in a union of only the types included by `dhall-kubernetes`), but, something to keep in mind.

If it could help with making the `dhall-haskell` implementation more performant then that would be great... I'm currently staring at the output of a `dhall <<< './Pipeline.dhall'` command that took eleven and a half minutes just to return a type error 😢

**Comment by f-f** [comment]
@ari-becker some thoughts:
- 11:30 for evaluation is definitely worth reporting and profiling in a `dhall-haskell` issue, as there might be some low-hanging fruit in there, and if you wish to help I'm sure you'd get lots of pointers for where to look
- The generation of the Union type would be of help only for people that want for some reason to send to `kubectl` a whole bunch of objects of different types (see #48)
  I'll also generate a record with all the types and one for defaults, and I suspect they will be most used
- IIRC there's a proposal somewhere to add merging of union types

**Comment by ari-becker** [comment]
> I'll also generate a record with all the types and one for defaults, and I suspect they will be most used

Please do, I'm currently managing `Imports.dhall` and `ImportTypes.dhall` with separate entries per Kubernetes API object, having to manually add new API objects to each one and re-`dhall freeze` them each time I need a new one, just because there isn't a `defaults/package.dhall` and `types/package.dhall` is a serious headache. Adding default and type packages would be much appreciated.
