### ISSUE TITLE
Update v1.0.0 to support Dhall 9.0.0?

### ISSUE THREAD

**Issue by ari-becker** [arianvp/dhall-kubernetes#73]
`dhall-kubernetes` at tag v1.0.0 still uses the old Optional literal syntax, which is no longer permitted in Dhall 9.0.0.

Can we get a `v1.1.0` tag which replaces the old Optional literal syntax with `Some` and `None` so that we can stay up to date?

**Comment by f-f** [comment]
I think this would require branching master (and doing the change and releasing the tag) from the latest commit before #57 was merged - because that introduces the new Haskell generator, which has the new API as a baked-in assumption so I wouldn't recommend modifying it but rather the Python generator.

I'm fine with this if someone wants to do it, but I won't be able to look at this myself for a while

Alternatively if you're able to upgrade to the latest API we can merge #72 and release `v2.0.0` from there

**Comment by ari-becker** [comment]
@f-f Yeah, I think we could upgrade to the latest API, if the merge for #72 and a v2.0.0 release happened pretty soon, we just don't want to have to be stuck on an older version of Dhall because of a dependency 👍

**Comment by f-f** [comment]
Cool! I'll fix the diff (it's showing +100k lines of additions, which is not right) and merge later today then 🙂

**Comment by f-f** [comment]
@ari-becker I merged #72, would you like to try to upgrade to the latest master (4ad58156b7fdbbb6da0543d8b314df899feca077) before I cut `2.0.0`?

**Comment by ari-becker** [comment]
@f-f I'm migrating one of our private downstream repos now to `4ad5815`, so far, no issues :) A few stumbles along the way, but nothing unexpected with such a massive change to the API surface.

If you see it working for your use-cases as well, I think you can go ahead and cut `2.0.0`... if I see anything over the course of the migration, worst-case scenario just cut some minor/patch tag.

**Comment by Gabriella439** [comment]
I'll mark this closed as `dhall-kubernetes` is currently being built with an even newer `dhall-1.27.0` version
