### ISSUE TITLE
Generate multiple types based on k8s version?

### ISSUE THREAD

**Issue by amarrella** [arianvp/dhall-kubernetes#75]
Hi :) would it be possible to support multiple kubernetes (minor) versions at once?
While the versions are backward compatible, i'd like to restrict users of the clusters we own to the subset of the api matching the kubernetes version running to avoid confusion.

Something like creating different directories (1.13 1.14 1.15) would work best i think, so all versions can keep up with the generator at the same time. 

What do you think?

**Comment by f-f** [comment]
This was briefly touched on in #4, but at the time we didn't deem it necessary

This said, this would be cool by me, and I suppose it would be a matter of mostly doing some Nix adjustments to get the build to generate everything. cc @arianvp 

The only complication I can foresee in this is the fact that we have [a big deny-list](https://github.com/dhall-lang/dhall-kubernetes/blob/master/dhall-kubernetes-generator/src/Dhall/Kubernetes/Data.hs) of objects that shouldn't go in the default record/types (because they overlap in name but have a different namespace. This happens because objects get promoted from alpha → beta → stable, and the old versions cannot be removed for backwards-compatibility reasons).
This list is written with the latest version in mind, and older versions might require a subset of it, and finding the correct subset might be a lot of work

**Comment by amarrella** [comment]
Hmm, good point on the deny list.

How about maintaining separate lists (in a dhall file?) per version that is supported? I think once defined for a version that won't change anyway, so the work would be once per version more or less and maybe just the last `n` versions (where `n` is a small, manageable number like 2 or 3) are officially maintained in case of bugs.

But I totally understand if this is too burdensome and you prefer to support one version only! :) 
Thanks to Kubernetes backward compatibility it's not a big deal anyway,

**Comment by JamesGuthrie** [comment]
We are currently running into this problem as well - it would be great to take advantage of the new syntax with inline defaults, but our Kubernetes cluster is on v1.13.

**Comment by amarrella** [comment]
Revisiting this issue, with #97 the version of kubernetes targeted by this repository is now 1.16. 

This is a problem for us as updating kubernetes version is not a light thing, and although the API is backward compatible we face a forward compatibility issue here if we are trying to apply 1.16 manifests to older clusters. In our case we are constrained by our cloud provider (AWS) to use 1.14 - even though it's officially EOL since a few weeks.

Looking on the deny list again, since we have the old list in the previous commit, do you think it would be reasonable to have a generator per version? (with no guarantee from the maintainers, if something is wrong it should be contributed)

**Comment by Gabriella439** [comment]
@amarrella: Yes, I believe we can support multiple versions just fine.  I think the main thing I need from you is what you would like the directory/file layout to look like if we did so

**Comment by amarrella** [comment]
@Gabriel439 thanks! I think we should just shift what is in the root right now into a versioned directory. So we can have:
```
/
/1.14
/1.14/package.dhall
/1.14/schemas.dhall
/1.14/types/
/1.14/defaults/
/1.14/schemas/
/1.15
/1.15/package.dhall
/1.15/schemas.dhall
/1.15/types/
/1.15/defaults/
/1.15/schemas/
/1.16
/1.16/package.dhall
/1.16/schemas.dhall
/1.16/types/
/1.16/defaults/
/1.16/schemas/
```
... etc.
In the root we would also keep like it is now the generator, nix stuff, docs, scripts, etc.

Do you think it's reasonable?

**Comment by Gabriella439** [comment]
@amarrella: Yeah, that seems reasonable to me!
